"use client";

import { useState } from "react";

import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { GitPullRequest, Play, Check } from "lucide-react";
import { useToast } from "@/components/ui/toast";

export interface PublishDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onPublished: () => void;
}

type Mode = "commit" | "mr";

export function PublishDialog({ open, onOpenChange, onPublished }: PublishDialogProps) {
  const [mode, setMode] = useState<Mode>("commit");
  const [branch, setBranch] = useState("main");
  const [mrBranch, setMrBranch] = useState("feature/ci-pipeline");
  const [mrTitle, setMrTitle] = useState("Add CI/CD pipeline for Node.js project");
  const [description] = useState(
    "Added GitLab CI pipeline with Docker build, caching, and test stages generated by AI."
  );
  const [isSubmitting, setIsSubmitting] = useState(false);
  const { showToast } = useToast();

  const handleConfirm = () => {
    setIsSubmitting(true);
    setTimeout(() => {
      setIsSubmitting(false);
      onOpenChange(false);
      onPublished();
      showToast({
        variant: "success",
        title: "Pipeline published",
        description:
          mode === "commit"
            ? `Committed directly to ${branch}.`
            : `Merge request from ${mrBranch} created successfully.`,
      });
    }, 1200);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Commit &amp; push pipeline</DialogTitle>
          <DialogDescription>
            Choose how to publish these changes to Git. You can commit directly to your main branch
            or open a merge request for review.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 text-xs text-slate-200">
          <div className="space-y-2">
            <p className="text-[11px] font-medium text-slate-400">Publication mode</p>
            <div className="grid grid-cols-2 gap-2">
              <button
                type="button"
                onClick={() => setMode("commit")}
                className={`flex items-start gap-2 rounded-md border px-3 py-2 text-left text-xs ${
                  mode === "commit"
                    ? "border-emerald-500/60 bg-emerald-500/5"
                    : "border-slate-800 bg-slate-950/60 hover:bg-slate-900"
                }`}
              >
                <span className="mt-0.5 flex h-6 w-6 items-center justify-center rounded-full bg-emerald-500/15">
                  <Play className="h-3.5 w-3.5 text-emerald-300" />
                </span>
                <span>
                  <span className="flex items-center gap-1 text-xs font-medium text-slate-100">
                    Commit to main
                    {mode === "commit" && (
                      <Badge variant="success" className="text-[9px]">
                        Selected
                      </Badge>
                    )}
                  </span>
                  <span className="mt-0.5 block text-[11px] text-slate-400">
                    Ideal for small, low-risk changes and quick iteration.
                  </span>
                </span>
              </button>

              <button
                type="button"
                onClick={() => setMode("mr")}
                className={`flex items-start gap-2 rounded-md border px-3 py-2 text-left text-xs ${
                  mode === "mr"
                    ? "border-sky-500/60 bg-sky-500/5"
                    : "border-slate-800 bg-slate-950/60 hover:bg-slate-900"
                }`}
              >
                <span className="mt-0.5 flex h-6 w-6 items-center justify-center rounded-full bg-sky-500/15">
                  <GitPullRequest className="h-3.5 w-3.5 text-sky-300" />
                </span>
                <span>
                  <span className="flex items-center gap-1 text-xs font-medium text-slate-100">
                    Create merge request
                    {mode === "mr" && (
                      <Badge variant="secondary" className="text-[9px]">
                        Selected
                      </Badge>
                    )}
                  </span>
                  <span className="mt-0.5 block text-[11px] text-slate-400">
                    Open a code review flow with a dedicated CI pipeline branch.
                  </span>
                </span>
              </button>
            </div>
          </div>

          {mode === "commit" ? (
            <div className="space-y-2">
              <p className="text-[11px] font-medium text-slate-400">Target branch</p>
              <Select
                value={branch}
                onChange={(e) => setBranch(e.target.value)}
                className="h-8 text-xs"
              >
                <option value="main">main</option>
                <option value="develop">develop</option>
              </Select>
            </div>
          ) : (
            <div className="space-y-3">
              <div>
                <p className="text-[11px] font-medium text-slate-400">
                  Source branch &amp; title
                </p>
                <div className="mt-1 grid gap-2 sm:grid-cols-2">
                  <input
                    value={mrBranch}
                    onChange={(e) => setMrBranch(e.target.value)}
                    className="h-8 rounded-md border border-slate-800 bg-slate-950 px-2 text-xs text-slate-100 outline-none focus-visible:ring-2 focus-visible:ring-sky-500"
                    placeholder="feature/ci-pipeline"
                  />
                  <input
                    value={mrTitle}
                    onChange={(e) => setMrTitle(e.target.value)}
                    className="h-8 rounded-md border border-slate-800 bg-slate-950 px-2 text-xs text-slate-100 outline-none focus-visible:ring-2 focus-visible:ring-sky-500"
                    placeholder="Add CI/CD pipeline"
                  />
                </div>
              </div>
              <div>
                <p className="text-[11px] font-medium text-slate-400">Description (AI generated)</p>
                <div className="mt-1 rounded-md border border-slate-800 bg-slate-950 px-2 py-2 text-[11px] text-slate-300">
                  {description}
                </div>
              </div>
            </div>
          )}

          <div className="mt-3 flex items-center justify-between border-t border-slate-800 pt-3 text-[11px] text-slate-500">
            <p>Nothing will be pushed until you confirm.</p>
            <div className="flex gap-2">
              <Button
                type="button"
                variant="secondary"
                className="h-8 px-3 text-xs"
                onClick={() => onOpenChange(false)}
                disabled={isSubmitting}
              >
                Cancel
              </Button>
              <Button
                type="button"
                className="h-8 gap-1.5 bg-emerald-500 px-3 text-xs text-slate-950 hover:bg-emerald-400"
                onClick={handleConfirm}
                disabled={isSubmitting}
              >
                {isSubmitting ? (
                  <>
                    <span className="h-3 w-3 animate-spin rounded-full border border-emerald-900 border-t-transparent" />
                    Confirming…
                  </>
                ) : (
                  <>
                    <Check className="h-3.5 w-3.5" />
                    Confirm
                  </>
                )}
              </Button>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}


