"use client";

import { motion } from "framer-motion";
import { Terminal, Zap, Shield, GitMerge, Users, Globe } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

export default function MarketingPage() {
  return (
    <div className="relative overflow-hidden">
      {/* background accents */}
      <div className="pointer-events-none absolute inset-0">
        <div className="absolute -left-40 top-0 h-72 w-72 rounded-full bg-sky-500/10 blur-3xl" />
        <div className="absolute bottom-0 right-[-120px] h-80 w-80 rounded-full bg-purple-500/10 blur-3xl" />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,_rgba(15,23,42,0)_0,_rgba(15,23,42,0.9)_55%,_rgba(15,23,42,1)_100%)]" />
      </div>

      <main className="relative mx-auto flex max-w-6xl flex-col gap-20 px-6 py-12 md:py-16">
        {/* Hero */}
        <section className="grid gap-10 md:grid-cols-[minmax(0,1.2fr)_minmax(0,1fr)] md:items-center">
          <div className="space-y-6">
            <motion.div
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="inline-flex items-center gap-2 rounded-full border border-slate-800 bg-slate-900/80 px-3 py-1 text-[11px] text-slate-300"
            >
              <span className="flex h-5 w-5 items-center justify-center rounded-full bg-sky-500/10">
                <Zap className="h-3 w-3 text-sky-400" />
              </span>
              <span className="font-medium">New</span>
              <span className="text-slate-500">
                Generate CI/CD pipelines without hand-written YAML.
              </span>
            </motion.div>

            <motion.h1
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.05 }}
              className="text-balance text-4xl font-semibold leading-tight sm:text-5xl"
            >
              <span className="bg-gradient-to-r from-sky-400 via-blue-400 to-purple-500 bg-clip-text text-transparent">
                Self-Deploy: CI/CD без DevOps
              </span>
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.12 }}
              className="max-w-xl text-sm text-slate-300 sm:text-base"
            >
              Автоматическая генерация и проверка CI/CD пайплайнов за секунды.
              Self-Deploy анализирует репозиторий, подбирает лучшие практики и
              запускает безопасные пайплайны без участия DevOps.
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.18 }}
              className="flex flex-wrap items-center gap-3"
            >
              <Button className="h-10 px-5 text-sm font-medium">
                Get started
              </Button>
              <Button
                variant="outline"
                className="h-10 border-slate-700 bg-slate-950/60 px-5 text-sm"
              >
                Live demo
              </Button>
              <p className="text-[11px] text-slate-500">
                Безопасная интеграция с GitLab, GitHub и Jenkins.
              </p>
            </motion.div>
          </div>

          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.1 }}
          >
            <Card className="relative border-slate-800 bg-slate-950/90">
              <CardHeader className="flex flex-row items-center justify-between pb-3">
                <div className="flex items-center gap-2">
                  <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-900">
                    <Terminal className="h-4 w-4 text-sky-400" />
                  </div>
                  <div>
                    <CardTitle className="text-xs font-medium">
                      Pipeline preview
                    </CardTitle>
                    <CardDescription className="text-[11px] text-slate-500">
                      .gitlab-ci.yml • generated by AI
                    </CardDescription>
                  </div>
                </div>
                <span className="rounded-full bg-emerald-500/10 px-2 py-0.5 text-[10px] font-medium text-emerald-300">
                  CI passing
                </span>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="rounded-lg border border-slate-800 bg-slate-950/90">
                  <div className="flex items-center gap-1 border-b border-slate-800 bg-slate-900/80 px-3 py-1.5 text-[10px] text-slate-400">
                    <span className="h-2 w-2 rounded-full bg-red-500/80" />
                    <span className="h-2 w-2 rounded-full bg-amber-400/80" />
                    <span className="h-2 w-2 rounded-full bg-emerald-500/80" />
                    <span className="ml-2">gitlab-ci • main</span>
                  </div>
                  <div className="space-y-1 px-3 py-3 font-mono text-[11px] text-slate-100">
                    <p className="text-slate-400">
{`image: node:18-alpine`}
                    </p>
                    <p>
                      <span className="text-sky-300">stages</span>:{" "}
                      <span className="text-emerald-300">
                        [lint, test, build]
                      </span>
                    </p>
                    <p>
                      <span className="text-sky-300">cache</span>:{" "}
                      <span className="text-emerald-300">node_modules/</span>
                    </p>
                    <p>
                      <span className="text-sky-300">lint</span>:{" "}
                      <span className="text-amber-300">
                        npm run lint
                      </span>
                    </p>
                    <p>
                      <span className="text-sky-300">build</span>:{" "}
                      <span className="text-amber-300">
                        docker build -t app .
                      </span>
                    </p>
                  </div>
                </div>
                <p className="text-[11px] text-slate-500">
                  Self-Deploy подбирает оптимальный пайплайн под ваш стек за
                  считанные секунды — от анализа репозитория до финальной
                  YAML-конфигурации.
                </p>
              </CardContent>
            </Card>
          </motion.div>
        </section>

        {/* Features */}
        <section className="space-y-6">
          <div className="flex items-center justify-between gap-4">
            <div>
              <h2 className="text-sm font-semibold text-slate-100">
                Что делает Self-Deploy
              </h2>
              <p className="mt-1 text-xs text-slate-400">
                Автоматизируйте CI/CD во всех репозиториях — без шаблонов и
                копипасты.
              </p>
            </div>
          </div>
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
            <FeatureCard
              icon={<GitMerge className="h-4 w-4 text-sky-400" />}
              title="Auto-detection"
              description="Recognizes stack (Node, Go, Python) instantly и подбирает подходящие шаги пайплайна."
            />
            <FeatureCard
              icon={<Zap className="h-4 w-4 text-amber-300" />}
              title="AI generator"
              description="Builds optimized pipelines without шаблонов — конфигурация под ваш проект."
            />
            <FeatureCard
              icon={<Shield className="h-4 w-4 text-emerald-300" />}
              title="Security first"
              description="Validates dangerous commands вроде rm -rf и подсвечивает риски до деплоя."
            />
            <FeatureCard
              icon={<Globe className="h-4 w-4 text-purple-300" />}
              title="Multi-platform"
              description="Supports GitLab CI и Jenkins — одна модель для разных систем."
            />
          </div>
        </section>

        {/* For whom */}
        <section className="space-y-6">
          <div className="flex items-center justify-between gap-4">
            <div>
              <h2 className="text-sm font-semibold text-slate-100">
                Для кого
              </h2>
              <p className="mt-1 text-xs text-slate-400">
                Разные роли — единый способ управлять пайплайнами.
              </p>
            </div>
          </div>
          <div className="grid gap-4 md:grid-cols-3">
            <AudienceCard
              icon={<Terminal className="h-4 w-4 text-sky-400" />}
              title="Для разработчиков"
              description="Stop writing YAML manually. Сфокусируйтесь на продукте, а не на синтаксисе CI."
            />
            <AudienceCard
              icon={<Users className="h-4 w-4 text-emerald-300" />}
              title="Для команд"
              description="Standardize pipelines across repos. Один стиль, один набор правил и автоматическая генерация."
            />
            <AudienceCard
              icon={<Shield className="h-4 w-4 text-amber-300" />}
              title="Для компаний"
              description="Enforce security policies. Централизованный контроль над командами и командами в пайплайнах."
            />
          </div>
        </section>
      </main>
    </div>
  );
}

interface FeatureCardProps {
  icon: React.ReactNode;
  title: string;
  description: string;
}

function FeatureCard({ icon, title, description }: FeatureCardProps) {
  return (
    <motion.div
      whileHover={{ y: -4, scale: 1.01 }}
      transition={{ type: "spring", stiffness: 260, damping: 20 }}
    >
      <Card className="h-full border-slate-800/80 bg-slate-900/80">
        <CardHeader className="space-y-3">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-900/90">
            {icon}
          </div>
          <CardTitle className="text-sm">{title}</CardTitle>
          <CardDescription className="text-xs text-slate-400">
            {description}
          </CardDescription>
        </CardHeader>
      </Card>
    </motion.div>
  );
}

interface AudienceCardProps {
  icon: React.ReactNode;
  title: string;
  description: string;
}

function AudienceCard({ icon, title, description }: AudienceCardProps) {
  return (
    <Card className="h-full border-slate-800/80 bg-slate-900/80">
      <CardHeader className="space-y-3">
        <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-900/90">
          {icon}
        </div>
        <CardTitle className="text-sm">{title}</CardTitle>
        <CardDescription className="text-xs text-slate-400">
          {description}
        </CardDescription>
      </CardHeader>
    </Card>
  );
}

