# Generated GitLab CI (auto)
stages:
  - pre_checks
  - lint
  - type_check
  - security
  - test
  - docker_build
  - docker_push
  - migration
  - cleanup

# Triggers (from user_settings.triggers)
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'





# Common variables
variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE"
  DOCKER_TAG: "$CI_COMMIT_SHORT_SHA"
  JAVA_VERSION: "21"
  BUILD_TOOL: "maven"

  # Required CI/CD variables for this pipeline (configure in GitLab settings)
  # CI_REGISTRY: GitLab container registry URL (usually predefined)
  # CI_REGISTRY_USER: registry username for docker login
  # CI_REGISTRY_PASSWORD: registry password/token for docker login
  # KUBECONFIG_CONTENT: base64-encoded kubeconfig for Kubernetes deploy

# User variables (inlined - prefer CI platform variables for secrets)

pre_checks:
  stage: pre_checks
  image: maven:3.9-eclipse-temurin-21
  script:
    - mvn --version
    - echo "Basic repo checks (lint config, presence of tests, dockerfile...)"

lint:
  stage: lint
  image: maven:3.9-eclipse-temurin-21
  script:
    - |
      # Находим директорию с pom.xml
      if [ -f "pom.xml" ]; then
        mvn checkstyle:check -Dcheckstyle.failOnViolation=false || true
        mvn spotbugs:check -Dspotbugs.failOnError=false || true
      else
        # Ищем pom.xml в поддиректориях
        POM_DIR=$(find . -name "pom.xml" -type f | head -1 | xargs dirname)
        if [ -n "$POM_DIR" ]; then
          cd "$POM_DIR"
          mvn checkstyle:check -Dcheckstyle.failOnViolation=false || true
          mvn spotbugs:check -Dspotbugs.failOnError=false || true
        else
          echo "POM file not found, skipping lint"
        fi
      fi
  artifacts:
    paths:
      - target/spotbugsXml.xml
    when: always
type_check:
  stage: type_check
  image: maven:3.9-eclipse-temurin-21
  script:
    - |
      # Находим директорию с pom.xml
      if [ -f "pom.xml" ]; then
        mvn compile
      else
        # Ищем pom.xml в поддиректориях
        POM_DIR=$(find . -name "pom.xml" -type f | head -1 | xargs dirname)
        if [ -n "$POM_DIR" ]; then
          cd "$POM_DIR"
          mvn compile
        else
          echo "POM file not found"
          exit 1
        fi
      fi

security:
  stage: security
  image: maven:3.9-eclipse-temurin-21
  script:
    - |
      # Находим директорию с pom.xml
      if [ -f "pom.xml" ]; then
        mvn org.owasp:dependency-check-maven:check || true
        mvn com.github.spotbugs:spotbugs-maven-plugin:check || true
      else
        # Ищем pom.xml в поддиректориях
        POM_DIR=$(find . -name "pom.xml" -type f | head -1 | xargs dirname)
        if [ -n "$POM_DIR" ]; then
          cd "$POM_DIR"
          mvn org.owasp:dependency-check-maven:check || true
          mvn com.github.spotbugs:spotbugs-maven-plugin:check || true
        else
          echo "POM file not found, skipping security checks"
        fi
      fi
  artifacts:
    paths:
      - target/dependency-check-report.html
      - target/spotbugsXml.xml
    expire_in: 1 week

test:
  stage: test
  
  image: maven:3.9-eclipse-temurin-21
  
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .m2/repository
  
  before_script:
    - export MAVEN_OPTS="-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"
  
  script:
    - |
      # Находим директорию с pom.xml
      if [ -f "pom.xml" ]; then
        mvn test || true
        mvn jacoco:report || true
      else
        # Ищем pom.xml в поддиректориях
        POM_DIR=$(find . -name "pom.xml" -type f | head -1 | xargs dirname)
        if [ -n "$POM_DIR" ]; then
          cd "$POM_DIR"
          mvn test || true
          mvn jacoco:report || true
        else
          echo "POM file not found, skipping tests"
        fi
      fi
  
  coverage: '/Total.*?([0-9]{1,3})%/'
  
  artifacts:
    when: always
    paths:
      - target/site/jacoco/
      - target/surefire-reports/
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
    expire_in: 1 week
docker_build:
  stage: docker_build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - echo "Building api-gateway/Dockerfile..."
    - docker build -f api-gateway/Dockerfile -t $CI_REGISTRY_IMAGE-api-gateway:$CI_COMMIT_SHORT_SHA api-gateway
    - docker save -o image-api_gateway.tar $CI_REGISTRY_IMAGE-api-gateway:$CI_COMMIT_SHORT_SHA || true
    - echo "Building tg_bot/Dockerfile..."
    - docker build -f tg_bot/Dockerfile -t $CI_REGISTRY_IMAGE-tg_bot:$CI_COMMIT_SHORT_SHA tg_bot
    - docker save -o image-tg_bot.tar $CI_REGISTRY_IMAGE-tg_bot:$CI_COMMIT_SHORT_SHA || true
    - echo "Building api-T-connector/Dockerfile..."
    - docker build -f api-T-connector/Dockerfile -t $CI_REGISTRY_IMAGE-api-t-connector:$CI_COMMIT_SHORT_SHA api-T-connector
    - docker save -o image-api_t_connector.tar $CI_REGISTRY_IMAGE-api-t-connector:$CI_COMMIT_SHORT_SHA || true
    - echo "Building company-info/Dockerfile..."
    - docker build -f company-info/Dockerfile -t $CI_REGISTRY_IMAGE-company-info:$CI_COMMIT_SHORT_SHA company-info
    - docker save -o image-company_info.tar $CI_REGISTRY_IMAGE-company-info:$CI_COMMIT_SHORT_SHA || true
    - echo "Building definition-of-anomaly/Dockerfile..."
    - docker build -f definition-of-anomaly/Dockerfile -t $CI_REGISTRY_IMAGE-definition-of-anomaly:$CI_COMMIT_SHORT_SHA definition-of-anomaly
    - docker save -o image-definition_of_anomaly.tar $CI_REGISTRY_IMAGE-definition-of-anomaly:$CI_COMMIT_SHORT_SHA || true
  artifacts:
    paths:
      - image-api_gateway.tar
      - image-tg_bot.tar
      - image-api_t_connector.tar
      - image-company_info.tar
      - image-definition_of_anomaly.tar

docker_push_api_gateway:
  stage: docker_push
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  dependencies:
    - docker_build
  script:
    - docker load -i image-api_gateway.tar || true
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    - docker push $CI_REGISTRY_IMAGE-api-gateway:$CI_COMMIT_SHORT_SHA
docker_push_tg_bot:
  stage: docker_push
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  dependencies:
    - docker_build
  script:
    - docker load -i image-tg_bot.tar || true
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    - docker push $CI_REGISTRY_IMAGE-tg_bot:$CI_COMMIT_SHORT_SHA
docker_push_api_t_connector:
  stage: docker_push
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  dependencies:
    - docker_build
  script:
    - docker load -i image-api_t_connector.tar || true
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    - docker push $CI_REGISTRY_IMAGE-api-t-connector:$CI_COMMIT_SHORT_SHA
docker_push_company_info:
  stage: docker_push
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  dependencies:
    - docker_build
  script:
    - docker load -i image-company_info.tar || true
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    - docker push $CI_REGISTRY_IMAGE-company-info:$CI_COMMIT_SHORT_SHA
docker_push_definition_of_anomaly:
  stage: docker_push
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  dependencies:
    - docker_build
  script:
    - docker load -i image-definition_of_anomaly.tar || true
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    - docker push $CI_REGISTRY_IMAGE-definition-of-anomaly:$CI_COMMIT_SHORT_SHA

migration:
  stage: migration
  image: maven:3.9-eclipse-temurin-21
  script:
    - |
      # Находим директорию с pom.xml
      if [ -f "pom.xml" ]; then
        POM_DIR="."
      else
        POM_DIR=$(find . -name "pom.xml" -type f | head -1 | xargs dirname)
        if [ -n "$POM_DIR" ]; then
          cd "$POM_DIR"
        else
          echo "POM file not found, skipping migrations"
          exit 0
        fi
      fi
    - echo "No migration tool detected for Spring Boot."

cleanup:
  stage: cleanup
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker system prune -f || true