# Generated GitLab CI (auto)
stages:
  - pre_checks
  - lint
  - type_check
  - security
  - test
  - build

# Triggers (from user_settings.triggers)
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'





# Common variables
variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE"
  DOCKER_TAG: "$CI_COMMIT_SHORT_SHA"
  JAVA_VERSION: "17"
  BUILD_TOOL: "gradle"

  # Required CI/CD variables for this pipeline (configure in GitLab settings)
  # CI_REGISTRY: GitLab container registry URL (usually predefined)
  # CI_REGISTRY_USER: registry username for docker login
  # CI_REGISTRY_PASSWORD: registry password/token for docker login
  # KUBECONFIG_CONTENT: base64-encoded kubeconfig for Kubernetes deploy

# User variables (inlined - prefer CI platform variables for secrets)

pre_checks:
  stage: pre_checks
  image: gradle:8.5-jdk17
  script:
    - ./gradlew --version || gradle --version || true
    - echo "Basic repo checks (lint config, presence of tests, dockerfile...)"

lint:
  stage: lint
  image: gradle:8.5-jdk17
  script:
    - |
      if [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
        ./gradlew checkstyleMain --continue || true
        ./gradlew spotbugsMain --continue || true
      else
        GRADLE_DIR=$(find . -name "build.gradle*" -type f | head -1 | xargs dirname)
        if [ -n "$GRADLE_DIR" ]; then
          cd "$GRADLE_DIR"
          ./gradlew checkstyleMain --continue || true
          ./gradlew spotbugsMain --continue || true
        else
          echo "Gradle build file not found, skipping lint"
        fi
      fi
  artifacts:
    paths:
      - build/reports/
    when: always
type_check:
  stage: type_check
  image: gradle:8.5-jdk17
  script:
    - |
      if [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
        ./gradlew classes
      else
        GRADLE_DIR=$(find . -name "build.gradle*" -type f | head -1 | xargs dirname)
        if [ -n "$GRADLE_DIR" ]; then
          cd "$GRADLE_DIR"
          ./gradlew classes
        else
          echo "Gradle build file not found"
          exit 1
        fi
      fi

security:
  stage: security
  image: gradle:8.5-jdk17
  script:
    - |
      if [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
        ./gradlew dependencyCheckAnalyze || true
        ./gradlew spotbugsMain || true
      else
        GRADLE_DIR=$(find . -name "build.gradle*" -type f | head -1 | xargs dirname)
        if [ -n "$GRADLE_DIR" ]; then
          cd "$GRADLE_DIR"
          ./gradlew dependencyCheckAnalyze || true
          ./gradlew spotbugsMain || true
        else
          echo "Gradle build file not found, skipping security checks"
        fi
      fi
  artifacts:
    paths:
      - build/reports/dependency-check-report.html
      - build/reports/spotbugs/
    expire_in: 1 week

test:
  stage: test
  
  image: gradle:8.5-jdk17
  
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .gradle/caches
  
  before_script:
    - export GRADLE_USER_HOME=${CI_PROJECT_DIR}/.gradle
  
  script:
    - |
      if [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
        ./gradlew test jacocoTestReport || gradle test jacocoTestReport || true
      else
        GRADLE_DIR=$(find . -name "build.gradle*" -type f | head -1 | xargs dirname)
        if [ -n "$GRADLE_DIR" ]; then
          cd "$GRADLE_DIR"
          ./gradlew test jacocoTestReport || gradle test jacocoTestReport || true
        else
          echo "Gradle build file not found, skipping tests"
        fi
      fi
  
  coverage: '/Total.*?([0-9]{1,3})%/'
  
  artifacts:
    when: always
    paths:
      - build/reports/jacoco/test/
      - build/test-results/
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
    expire_in: 1 week
build:
  stage: build
  image: gradle:8.5-jdk17
  script:
    - |
      if [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
        ./gradlew build -x test
      else
        GRADLE_DIR=$(find . -name "build.gradle*" -type f | head -1 | xargs dirname)
        if [ -n "$GRADLE_DIR" ]; then
          cd "$GRADLE_DIR"
          ./gradlew build -x test
        else
          echo "Gradle build file not found"
          exit 1
        fi
      fi
  artifacts:
    paths:
      - 'build/libs/*.jar'
    expire_in: 1 week