# Generated GitLab CI (auto)
stages:
  - pre_checks
  - lint
  - type_check
  - security
  - test
  - build
  - docker_build
  - docker_push
  - migration
  - cleanup

# Triggers (from user_settings.triggers)
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
      when: on_success

    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success




# Common variables
variables:
  DOCKER_IMAGE: "registry.example.com/team/java-gradle-app"
  DOCKER_TAG: "$CI_COMMIT_SHORT_SHA"
  JAVA_VERSION: "21"
  BUILD_TOOL: "gradle"

  # Required CI/CD variables for this pipeline (configure in GitLab settings)
  # CI_REGISTRY: GitLab container registry URL (usually predefined)
  # CI_REGISTRY_USER: registry username for docker login
  # CI_REGISTRY_PASSWORD: registry password/token for docker login
  # KUBECONFIG_CONTENT: base64-encoded kubeconfig for Kubernetes deploy

# User variables (inlined - prefer CI platform variables for secrets)

pre_checks:
  stage: pre_checks
  image: gradle:21-jdk
  script:
    - ./gradlew --version || gradle --version || true
    - echo "Basic repo checks (lint config, presence of tests, dockerfile...)"

lint:
  stage: lint
  image: gradle:21-jdk
  script:
    - ./gradlew checkstyleMain --continue || true
    - ./gradlew spotbugsMain --continue || true
  artifacts:
    paths:
      - build/reports/
    when: always
type_check:
  stage: type_check
  image: gradle:21-jdk
  script:
    - ./gradlew classes

security:
  stage: security
  image: gradle:21-jdk
  script:
    - ./gradlew dependencyCheckAnalyze || true
    - ./gradlew spotbugsMain || true
  artifacts:
    paths:
      - build/reports/dependency-check-report.html
      - build/reports/spotbugs/
    expire_in: 1 week

test:
  stage: test
  
  image: gradle:21-jdk
  
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .gradle/caches
  
  before_script:
    - export GRADLE_USER_HOME=${CI_PROJECT_DIR}/.gradle
  
  script:
    - ./gradlew test jacocoTestReport || gradle test jacocoTestReport || true
  
  coverage: '/Total.*?([0-9]{1,3})%/'
  
  artifacts:
    when: always
    paths:
      - build/reports/jacoco/test/
      - build/test-results/
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
    expire_in: 1 week
build:
  stage: build
  image: gradle:21-jdk
  script:
    - ./gradlew build -x test
  artifacts:
    paths:
      - 'build/libs/*.jar'
    expire_in: 1 week
docker_build:
  stage: docker_build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  dependencies:
    - build
  script:
    - docker build -f Dockerfile -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker save -o image.tar $DOCKER_IMAGE:$DOCKER_TAG || true
  artifacts:
    paths:
      - image.tar
docker_push:
  stage: docker_push
  image: docker:24
  services:
    - docker:24-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
migration:
  stage: migration
  image: gradle:21-jdk
  script:
    - echo "No migration tool detected for Spring Boot."

cleanup:
  stage: cleanup
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker system prune -f || true
