# Generated GitLab CI (auto)
stages:
  - pre_checks
  - lint
  - type_check
  - security
  - test
  - build
  - docker_build
  - docker_push
  - migration
  - deploy
  - post_deploy
  - cleanup

# Triggers (from user_settings.triggers)
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "develop" && $CI_PIPELINE_SOURCE == "push"'
      when: on_success

    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success

    - if: '$CI_COMMIT_TAG =~ /v*/ && $CI_PIPELINE_SOURCE == "push"'
      when: on_success



# Common variables
variables:
  DOCKER_IMAGE: "registry.example.com/team/java-app"
  DOCKER_TAG: "$CI_COMMIT_SHORT_SHA"
  JAVA_VERSION: "17"
  BUILD_TOOL: "maven"

  # Required CI/CD variables for this pipeline (configure in GitLab settings)
  # CI_REGISTRY: GitLab container registry URL (usually predefined)
  # CI_REGISTRY_USER: registry username for docker login
  # CI_REGISTRY_PASSWORD: registry password/token for docker login
  # KUBECONFIG_CONTENT: base64-encoded kubeconfig for Kubernetes deploy

# User variables (inlined - prefer CI platform variables for secrets)

pre_checks:
  stage: pre_checks
  image: maven:17-eclipse-temurin
  script:
    - mvn --version
    - echo "Basic repo checks (lint config, presence of tests, dockerfile...)"

lint:
  stage: lint
  image: maven:17-eclipse-temurin
  script:
    - mvn checkstyle:check -Dcheckstyle.failOnViolation=false || true
    - mvn spotbugs:check -Dspotbugs.failOnError=false || true
  artifacts:
    paths:
      - target/spotbugsXml.xml
    when: always
type_check:
  stage: type_check
  image: maven:17-eclipse-temurin
  script:
    - mvn compile

security:
  stage: security
  image: maven:17-eclipse-temurin
  script:
    - mvn org.owasp:dependency-check-maven:check || true
    - mvn com.github.spotbugs:spotbugs-maven-plugin:check || true
  artifacts:
    paths:
      - target/dependency-check-report.html
      - target/spotbugsXml.xml
    expire_in: 1 week

test:
  stage: test
  
  image: maven:17-eclipse-temurin
  
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .m2/repository
  
  before_script:
    - export MAVEN_OPTS="-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"
  
  script:
    - mvn test || true
    - mvn jacoco:report || true
  
  coverage: '/Total.*?([0-9]{1,3})%/'
  
  artifacts:
    when: always
    paths:
      - target/site/jacoco/
      - target/surefire-reports/
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
    expire_in: 1 week
build:
  stage: build
  image: maven:17-eclipse-temurin
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - 'target/*.jar'
    expire_in: 1 week
docker_build:
  stage: docker_build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  dependencies:
    - build
  script:
    - docker build -f Dockerfile -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker save -o image.tar $DOCKER_IMAGE:$DOCKER_TAG || true
  artifacts:
    paths:
      - image.tar
docker_push:
  stage: docker_push
  image: docker:24
  services:
    - docker:24-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
migration:
  stage: migration
  image: maven:17-eclipse-temurin
  script:
    - echo "No migration tool detected for Spring Boot."

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - echo "$KUBECONFIG_CONTENT" | base64 -d > kubeconfig
    - export KUBECONFIG=$CI_PROJECT_DIR/kubeconfig
    - kubectl apply -f k8s/ || true
  environment:
    name: production
post_deploy:
  stage: post_deploy
  image: maven:17-eclipse-temurin
  script:
    - mvn test -Dtest=*SmokeTest || mvn test -Dtest=*Smoke* || true

cleanup:
  stage: cleanup
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker system prune -f || true
