# Generated GitLab CI (auto)
stages:
  - pre_checks
  - lint
  - type_check
  - security
  - test
  - build
  - docker_build
  - docker_push
  - migration
  - deploy
  - post_deploy
  - cleanup

# Triggers (from user_settings.triggers)
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "develop" && $CI_PIPELINE_SOURCE == "push"'
      when: on_success

    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success

    - if: '$CI_COMMIT_TAG =~ /v*/ && $CI_PIPELINE_SOURCE == "push"'
      when: on_success



# Common variables
variables:
  DOCKER_IMAGE: "registry.example.com/team/typescript-app"
  DOCKER_TAG: "$CI_COMMIT_SHORT_SHA"
  NODE_VERSION: "18"

  # Required CI/CD variables for this pipeline (configure in GitLab settings)
  # CI_REGISTRY: GitLab container registry URL (usually predefined)
  # CI_REGISTRY_USER: registry username for docker login
  # CI_REGISTRY_PASSWORD: registry password/token for docker login
  # KUBECONFIG_CONTENT: base64-encoded kubeconfig for Kubernetes deploy

# User variables (inlined - prefer CI platform variables for secrets)

pre_checks:
  stage: pre_checks
  image: node:18
  script:
    - node --version
    - npm --version || yarn --version || true
    - echo "Basic repo checks (lint config, presence of tests, dockerfile...)"

lint:
  stage: lint
  image: node:18
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - npm ci || yarn install --frozen-lockfile || true
  script:
    - npm run lint || yarn lint || true
    - npx eslint . --ext .ts,.tsx --format json -o eslint-report.json || true
    - npx prettier --check "**/*.{ts,tsx,json}" || true
  artifacts:
    paths:
      - eslint-report.json
    expire_in: 1 week
type_check:
  stage: type_check
  image: node:18
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - npm ci || yarn install --frozen-lockfile || true
  script:
    - npm run type-check || yarn type-check || true
    - npx tsc --noEmit || true
  artifacts:
    paths:
      - tsconfig.tsbuildinfo
    expire_in: 1 week

security:
  stage: security
  image: node:18
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - npm ci || yarn install --frozen-lockfile || true
  script:
    - npm audit --audit-level=moderate || yarn audit --level moderate || true
    - npx snyk test --json || true
  artifacts:
    paths:
      - snyk-report.json
    expire_in: 1 week

test:
  stage: test
  
  image: node:18
  
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  
  before_script:
    - npm ci || yarn install --frozen-lockfile || true
  
  script:
    - npm test -- --ci --coverage || yarn test --ci --coverage || true
  
  
  artifacts:
    when: always
    paths:
      - coverage/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    expire_in: 1 week
build:
  stage: build
  image: node:18
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm ci || yarn install --frozen-lockfile || true
    - npm run build || yarn build || true
  artifacts:
    paths:
      - dist/
      - build/
    expire_in: 1 hour
docker_build:
  stage: docker_build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  dependencies:
    - build
  script:
    - docker build -f Dockerfile -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker save -o image.tar $DOCKER_IMAGE:$DOCKER_TAG || true
  artifacts:
    paths:
      - image.tar
docker_push:
  stage: docker_push
  image: docker:24
  services:
    - docker:24-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
migration:
  stage: migration
  image: node:18
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - npm ci || yarn install --frozen-lockfile || true
  script:
    - echo "Running migrations for Express..."
    - echo "No migration tool detected for Express. Supported: typeorm, sequelize, knex"
  only:
    - main
    - develop

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - echo "$KUBECONFIG_CONTENT" | base64 -d > kubeconfig
    - export KUBECONFIG=$CI_PROJECT_DIR/kubeconfig
    - kubectl apply -f k8s/ || true
  environment:
    name: production
post_deploy:
  stage: post_deploy
  image: node:18
  script:
    - npm ci || yarn install --frozen-lockfile || true
    - npm run test:smoke || yarn test:smoke || npm test -- --grep smoke || true

cleanup:
  stage: cleanup
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker system prune -f || true
